! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Initialization File
! 
! Generated by KPP-2.2.3 symbolic chemistry Kinetics PreProcessor
!       (http://www.cs.vt.edu/~asandu/Software/KPP)
! KPP is distributed under GPL, the general public licence
!       (http://www.gnu.org/copyleft/gpl.html)
! (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
! (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech
!     With important contributions from:
!        M. Damian, Villanova University, USA
!        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany
! 
! File                 : second_Initialize.f90
! Time                 : Thu Jun 24 16:19:59 2021
! Working directory    : /home/local/pzzhou/Scripts/Fortran/SOSAA/chemistry/sample_aerosol/KPP
! Equation file        : second.kpp
! Output root filename : second
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



MODULE second_Initialize

  USE second_Parameters, ONLY: dp, NVAR, NFIX
  IMPLICIT NONE

CONTAINS


! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Initialize - function to initialize concentrations
!   Arguments :
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

SUBROUTINE Initialize ( )


  USE second_Global

  INTEGER :: i
  REAL(kind=dp) :: x

  CFACTOR = 1.000000e+00_dp

  x = (0.)*CFACTOR
  DO i = 1, NVAR
    VAR(i) = x
  END DO

  x = (0.)*CFACTOR
  DO i = 1, NFIX
    FIX(i) = x
  END DO

! constant rate coefficients
  RCONST(1) = 1
  RCONST(2) = 1
  RCONST(3) = 1
  RCONST(4) = 1
  RCONST(5) = 1
  RCONST(6) = 1
  RCONST(7) = 1
  RCONST(8) = 1
  RCONST(9) = 1
  RCONST(10) = 1
  RCONST(11) = 1
  RCONST(12) = 1
  RCONST(13) = 1
  RCONST(14) = 1
  RCONST(15) = 1
  RCONST(16) = 1
  RCONST(17) = 1
  RCONST(18) = 1
  RCONST(19) = 1
  RCONST(20) = 1
  RCONST(21) = 1
  RCONST(22) = 1
  RCONST(2538) = 9.258e-11
  RCONST(3630) = 1.867e-11
  RCONST(3631) = 1.513e-11
  RCONST(3633) = 1.865e-11
! END constant rate coefficients

! INLINED initializations

! End INLINED initializations

      
END SUBROUTINE Initialize

! End of Initialize function
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



END MODULE second_Initialize

